site_name: zhangkangcool's blog
repo_url: https://github.com/zhangkangcool/zhangkangcool.github.io
edit_uri: edit/main/docs/
repo_name: zhangkangcool

site_author: zhangkangcool
site_description: ken's blog
copyright: zhangkangcool

markdown_extensions:

  - toc:

      permalink: True

  - footnotes

  - tables

  - markdown_checklist.extension

theme: readthedocs

