site_name: zhangkangcool's blog
repo_url: https://github.com/zhangkangcool/zhangkangcool.github.io
site_url: https://github.com/zhangkangcool/zhangkangcool.github.io
edit_uri: edit/main/docs/
repo_name: zhangkangcool

site_author: zhangkangcool
site_description: ken's blog
copyright: Copyright &copy; 2023 ~ now | zhangkangcool(ken)

markdown_extensions:

  - toc:   # 自动生成目录
      permalink: True

  - footnotes # 在文档底部自动生成脚注区域，并在引用处添加上标链接

  - tables    # 支持 Markdown 表格语法

  - admonition  #便利贴

  - markdown_checklist.extension  # 支持 GitHub 风格的任务列表

# TODO: 行号无法显示
  - codehilite:  # 是 MkDocs 内置的 Markdown 扩展，基于 Python Markdown 的 codehilite 插件，使用 Pygments 进行代码高亮
      guess_lang: false
      linenums: false
  - pymdownx.highlight: # 是 MkDocs 内置的 Markdown 扩展，基于 Python Markdown 的 codehilite 插件，使用 Pygments 进行代码高亮
      anchor_linenums: true
      line_spans: __span
      auto_title: true   # 显示标题，未设置则会显示代码的语言
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  #块嵌套
  - pymdownx.details #块折叠
  - pymdownx.keys # 样式：键盘按键


#theme: readthedocs
theme:
# reference http://www.cuishuaiwen.com:8000/zh/PROJECT/TECH-BLOG/mkdocs_and_material/#material_3
#  custom_dir: material/overrides # 自定义文件夹，对于个别页面，如果你不想使用主题的默认样式，可以在这里进行修改，使用里面的文件覆盖主题的默认文件。具体可以参考material官方文档。
  name: material # 主题名称，Material已经是最优秀的选择了，相信我。
  logo: assets/images/logo.jpeg # logo 图片
  language: en # 默认语言
  features: # 功能  
    - announce.dismiss # 可以叉掉公告的功能
    - content.action.edit # 编辑按钮，似乎没啥用
    - content.action.view # 查看按钮，似乎没啥用
    - content.code.annotate # 代码注释，具体不清楚
    - content.code.copy # 复制代码按钮
    # - content.code.select # 选择代码按钮
    # - content.tabs.link # 链接标签
    - content.tooltips # 不太清楚呢这个
    # - header.autohide # 自动隐藏header
    - navigation.expand # 默认展开导航栏
    - navigation.footer # 底部导航栏
    - navigation.indexes # 索引按钮可以直接触发文件，而不是只能点击其下属选项浏览，这个功能可以给对应的section提供很好的预览和导航功能
    # - navigation.instant # 瞬间加载 - 如果这个开着，那么语言切换后就会跳转至首页，所以我关掉了
    - navigation.instant.prefetch # 预加载
    - navigation.instant.progress # 进度条
    - navigation.path # 导航路径， 目前好像没啥用
    # - navigation.prune # 只构建可见的页面
    - navigation.sections # 导航栏的section
    - navigation.tabs # 顶级索引被作为tab
    - navigation.tabs.sticky # tab始终可见
    - navigation.top # 开启顶部导航栏
    - navigation.tracking # 导航栏跟踪
    - search.highlight # 搜索高亮
    - search.share # 搜索分享
    - search.suggest # 搜索建议
    - toc.follow # 目录跟踪-页面右侧的小目录
    # - toc.integrate # 目录跟踪集成到左侧大目录中
  palette:
    - media: "(prefers-color-scheme)" # 主题颜色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" # 浅色
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 深色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font: # 字体，大概率不需要换
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png # 网站图标 似乎不需要管
  icon: # 一些用到的icon
    logo: logo
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    tag:
      default-tag: fontawesome/solid/tag
      hardware-tag: fontawesome/solid/microchip
      software-tag: fontawesome/solid/laptop-code

plugins:
  - minify:  # 压缩 HTML、CSS、JavaScript 文件以提高加载速度
      minify_html: true

  - git-revision-date-localized:  # 显示文档的最后修改时间（基于 Git）
      type: date

  - search  # 内置搜索


# TODO: 此插件报编译错误
#  - git-authors: # 显示文档的 Git 作者和贡献统计

